apiVersion: apps/v1
kind: Deployment
metadata:
  name: sut
  labels:
    app: sut
    name: sut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sut
      name: sut
  template:
    metadata:
      labels:
        app: sut
        name: sut
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: sut
          image: sut:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: sut-http
              containerPort: 8080
