resources:
  - ../../base/qms-microservices
  - ../../base/qms-monolith
  - grafana
  - grafana-agent
  - loki
  - mimir
  - tempo
  - sut

replicas:
  # Microservices mode
  - name: qms-proxy
    count: 3
  - name: qms-rate
    count: 3
  - name: qms-alloc
    count: 3
  # Monolith mode
  - name: qms
    count: 3
