apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-logs
stringData:
  logs_remote_write_url: "http://loki:3100/loki/api/v1/push"
  logs_remote_write_username: ""
  logs_remote_write_password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-metrics
stringData:
  metrics_remote_write_url: "http://mimir:9009/api/v1/push"
  metrics_remote_write_username: ""
  metrics_remote_write_password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-agent-traces
stringData:
  traces_remote_write_url: "http://tempo:4317"
  traces_remote_write_username: ""
  traces_remote_write_password: ""
