apiVersion: v1
kind: ConfigMap
metadata:
  name: qms-config
data:
  config.yaml: |
    target: all
    otel_collector_target: grafana-agent-traces:4317

    server:
      http_port: 6789

    memberlist:
      join_addresses:
        - qms-gossip.default.svc.cluster.local
    
    proxy:
      rate_addresses:
        - dnssrv+qms-http.default.svc.cluster.local
      alloc_lb_strategy: round-robin
      alloc_addresses:
        - dnssrv+qms-http.default.svc.cluster.local
    
    alloc:
      storage:
        backend: raft
        raft:
          dir: /qms/data/raft/
          bind_address_from_hostname: true
          replica_id_override: ${REPLICA_ID_OVERRIDE}
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            capacity: 10

    rate:
      storage:
        backend: memory
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            algorithm: token-bucket
            unit: minute
            requests_per_unit: 120
        - namespace: namespace2
          resource: resource2
          strategy:
            algorithm: token-bucket
            unit: second
            requests_per_unit: 10