apiVersion: v1
kind: Service
metadata:
  name: qms
spec:
  clusterIP: None
  selector:
    app: qms
  ports:
    - name: qms-http
      protocol: TCP
      port: 6789
      targetPort: 6789
    - name: qms-gossip
      protocol: TCP
      port: 7946
      targetPort: 7946