apiVersion: v1
kind: Service
metadata:
  name: qms
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: qms
---
apiVersion: v1
kind: Service
metadata:
  name: qms-http
spec:
  clusterIP: None
  selector:
    app: qms
  ports:
    - name: http
      protocol: TCP
      port: 6789
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: qms-gossip
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: qms
  ports:
    - name: gossip
      protocol: TCP
      port: 7946
      targetPort: gossip
