apiVersion: v1
kind: ConfigMap
metadata:
  name: qms-rate-config
data:
  config.yaml: |
    target: rate
    otel_collector_target: grafana-agent-traces:4317

    server:
      http_port: 6789

    memberlist:
      join_addresses:
        - qms-rate.default.svc.cluster.local
    
    rate:
      storage:
        backend: memory
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            algorithm: fixed-window
            unit: second
            requests_per_unit: 25
        - namespace: namespace2
          resource: resource2
          strategy:
            algorithm: token-bucket
            unit: second
            requests_per_unit: 10
