apiVersion: v1
kind: Service
metadata:
  name: qms-rate
spec:
  clusterIP: None
  selector:
    app: qms-rate
  ports:
    - name: http
      protocol: TCP
      port: 6789
      targetPort: 6789
    - name: gossip
      protocol: TCP
      port: 7946
      targetPort: 7946