apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qms-rate
  labels:
    app: qms
    name: qms-rate
spec:
  serviceName: qms-rate
  replicas: 3
  selector:
    matchLabels:
      app: qms
      name: qms-rate
  template:
    metadata:
      labels:
        app: qms
        name: qms-rate
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6789'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - qms-rate
      containers:
        - name: qms-rate
          image: blinku/qms:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/app/configs/config.yaml"
            - "-config.expand-env=true"
          ports:
            - name: http
              protocol: TCP
              containerPort: 6789
            - name: gossip
              protocol: TCP
              containerPort: 7946
          volumeMounts:
            - name: qms-rate-config
              mountPath: /app/configs
            - name: qms-rate-data
              mountPath: /qms/data/raft
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: qms-rate-config
          configMap:
            name: qms-rate-config
        - name: qms-rate-data
          persistentVolumeClaim:
            claimName: qms-rate-data
  volumeClaimTemplates:
    - metadata:
        name: qms-rate-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi