apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qms-rate
  labels:
    app: qms-rate
spec:
  serviceName: qms-rate
  replicas: 1
  selector:
    matchLabels:
      app: qms-rate
  template:
    metadata:
      labels:
        app: qms-rate
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6789'
    spec:
      containers:
        - name: qms-rate
          image: qms:latest
          args:
            - "-config.file=/app/configs/config.yaml"
            - "-config.expand-env=true"
          ports:
            - name: http
              protocol: TCP
              containerPort: 6789
            - name: gossip
              protocol: TCP
              containerPort: 7946
          volumeMounts:
            - name: qms-rate-config
              mountPath: /app/configs
            - name: qms-rate-data
              mountPath: /qms/data/raft
      volumes:
        - name: qms-rate-config
          configMap:
            name: qms-rate-config
        - name: qms-rate-data
          persistentVolumeClaim:
            claimName: qms-rate-data
  volumeClaimTemplates:
    - metadata:
        name: qms-rate-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi