apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-metrics
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent-metrics
subjects:
  - kind: ServiceAccount
    name: grafana-agent-metrics
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent-metrics
  name: grafana-agent-metrics
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: grafana-agent-metrics-http-metrics
      port: 80
      targetPort: 80
  selector:
    name: grafana-agent-metrics
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-agent-metrics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-agent-metrics
  serviceName: grafana-agent-metrics
  template:
    metadata:
      labels:
        name: grafana-agent-metrics
    spec:
      containers:
        - args:
            - -config.expand-env
            - -config.file=/etc/agent/agent.yaml
            - -enable-features=integrations-next
            - -server.http.address=0.0.0.0:80
          command:
            - /bin/agent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: METRICS_REMOTE_WRITE_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-agent-metrics
                  key: metrics_remote_write_url
            - name: METRICS_REMOTE_WRITE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grafana-agent-metrics
                  key: metrics_remote_write_username
            - name: METRICS_REMOTE_WRITE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-agent-metrics
                  key: metrics_remote_write_password
          image: grafana/agent:v0.24.2
          imagePullPolicy: IfNotPresent
          name: grafana-agent-metrics
          ports:
            - containerPort: 80
              name: http-metrics
          volumeMounts:
            - mountPath: /var/lib/agent
              name: agent-wal
            - mountPath: /etc/agent
              name: grafana-agent-metrics
      serviceAccountName: grafana-agent-metrics
      volumes:
        - configMap:
            name: grafana-agent-metrics
          name: grafana-agent-metrics
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: agent-wal
        namespace: default
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
