apiVersion: v1
kind: ConfigMap
metadata:
  name: qms-proxy-config
data:
  config.yaml: |
    target: proxy
    otel_collector_target: grafana-agent-traces:4317

    server:
      http_port: 6789

    memberlist:
      join_addresses:
        - qms-proxy-gossip.default.svc.cluster.local

    proxy:
      rate_addresses:
        - dnssrv+qms-rate-http.default.svc.cluster.local
      alloc_lb_strategy: round-robin
      alloc_addresses:
        - dnssrv+qms-alloc-http.default.svc.cluster.local
