apiVersion: apps/v1
kind: Deployment
metadata:
  name: qms-proxy
  labels:
    app: qms-proxy
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '6789'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qms-proxy
  template:
    metadata:
      labels:
        app: qms-proxy
    spec:
      containers:
        - name: qms-proxy
          image: qms:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 6789
            - name: gossip
              protocol: TCP
              containerPort: 7946
          volumeMounts:
            - name: qms-proxy-config
              mountPath: /app/configs
      volumes:
        - name: qms-proxy-config
          configMap:
            name: qms-proxy-config