apiVersion: apps/v1
kind: Deployment
metadata:
  name: qms-proxy
  labels:
    app: qms
    name: qms-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qms
      name: qms-proxy
  template:
    metadata:
      labels:
        app: qms
        name: qms-proxy
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6789'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - qms-proxy
      containers:
        - name: qms-proxy
          image: blinku/qms:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/app/configs/config.yaml"
            - "-config.expand-env=true"
          ports:
            - name: http
              protocol: TCP
              containerPort: 6789
            - name: gossip
              protocol: TCP
              containerPort: 7946
          volumeMounts:
            - name: qms-proxy-config
              mountPath: /app/configs
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: qms-proxy-config
          configMap:
            name: qms-proxy-config