apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-auth-config
data:
  grafana.ini: |
    [auth]
    disable_login_form = true
    
    [auth.anonymous]
    enabled = true
    org_role = Admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-config
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        basicAuth: false
        isDefault: true
        editable: true
        version: 1
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"trace_id":"(\w+)"'
              name: trace_id
              url: "$${__value.raw}"
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir:9009/prometheus
        basicAuth: false
        isDefault: false
        editable: true
        version: 1
        jsonData:
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: tempo
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo:3200
        basicAuth: false
        isDefault: false
        editable: true
        version: 1
        apiVersion: 1
        uid: tempo
        jsonData:
          serviceMap:
            datasourceUid: Mimir
          tracesToLogs:
            datasourceUid: Loki
