target: all
otel_collector_target: grafana-agent-traces:4317

server:
  http_port: 6001

memberlist:
  bind_port: 10001
  join_addresses:
    - 127.0.0.1:10000
    - 127.0.0.1:10001
    - 127.0.0.1:10002

proxy:
  alloc_addresses:
    - 127.0.0.1:6000
    - 127.0.0.1:6001
    - 127.0.0.1:6002
  rate_addresses:
    - 127.0.0.1:6000
    - 127.0.0.1:6001
    - 127.0.0.1:6002

alloc:
  storage:
    backend: memory
  quotas:
    - namespace: namespace1
      resource: resource1
      strategy:
        capacity: 10

rate:
  storage:
    backend: memory
  quotas:
    - namespace: namespace1
      resource: resource1
      strategy:
        algorithm: token-bucket
        unit: minute
        requests_per_unit: 120
