apiVersion: v1
kind: ConfigMap
metadata:
  name: qms-alloc-config
data:
  config.yaml: |
    target: alloc
    otel_collector_target: grafana-agent-traces:4317

    server:
      http_port: 6789

    memberlist:
      join_members:
        - qms-alloc.default.svc.cluster.local
    
    kv:
      backend: raft

    alloc:
      backend: local
      local:
        dir: /tmp/qms/data/alloc
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            capacity: 10
