apiVersion: v1
kind: ConfigMap
metadata:
  name: qms-alloc-config
data:
  config.yaml: |
    target: alloc
    otel_collector_target: grafana-agent-traces:4317

    server:
      http_port: 6789

    memberlist:
      join_addresses:
        - qms-alloc-gossip.default.svc.cluster.local

    alloc:
      storage:
        backend: raft
        raft:
          dir: /qms/data/raft/
          host_from_hostname: true
          replica_id_override: ${REPLICA_ID_OVERRIDE}
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            capacity: 100
