apiVersion: v1
kind: Service
metadata:
  name: qms-alloc
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: qms
    name: qms-alloc
---
apiVersion: v1
kind: Service
metadata:
  name: qms-alloc-http
spec:
  clusterIP: None
  selector:
    app: qms
    name: qms-alloc
  ports:
    - name: http
      protocol: TCP
      port: 6789
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: qms-alloc-gossip
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: qms
    name: qms-alloc
  ports:
    - name: gossip
      protocol: TCP
      port: 7946
      targetPort: gossip
