apiVersion: v1
kind: Service
metadata:
  name: qms-alloc
spec:
  clusterIP: None
  selector:
    app: qms-alloc
  ports:
    - name: http
      protocol: TCP
      port: 6789
      targetPort: http
    - name: gossip
      protocol: TCP
      port: 7946
      targetPort: gossip