apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qms-alloc
  labels:
    app: qms-alloc
spec:
  serviceName: qms-alloc
  replicas: 1
  selector:
    matchLabels:
      app: qms-alloc
  template:
    metadata:
      labels:
        app: qms-alloc
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6789'
    spec:
      containers:
        - name: qms-alloc
          image: qms:latest
          args:
            - "-config.file=/app/configs/config.yaml"
            - "-config.expand-env=true"
          env:
            - name: REPLICA_ID_OVERRIDE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              protocol: TCP
              containerPort: 6789
            - name: gossip
              protocol: TCP
              containerPort: 7946
          volumeMounts:
            - name: qms-alloc-config
              mountPath: /app/configs
            - name: qms-alloc-data
              mountPath: /qms/data/raft
      volumes:
        - name: qms-alloc-config
          configMap:
            name: qms-alloc-config
        - name: qms-alloc-data
          persistentVolumeClaim:
            claimName: qms-alloc-data
  volumeClaimTemplates:
    - metadata:
        name: qms-alloc-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi