apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qms-alloc
  labels:
    app: qms
    name: qms-alloc
spec:
  serviceName: qms-alloc
  replicas: 3
  selector:
    matchLabels:
      app: qms
      name: qms-alloc
  template:
    metadata:
      labels:
        app: qms
        name: qms-alloc
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6789'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - qms-alloc
      containers:
        - name: qms-alloc
          image: blinku/qms:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/app/configs/config.yaml"
            - "-config.expand-env=true"
          env:
            - name: REPLICA_ID_OVERRIDE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              protocol: TCP
              containerPort: 6789
            - name: gossip
              protocol: TCP
              containerPort: 7946
          volumeMounts:
            - name: qms-alloc-config
              mountPath: /app/configs
            - name: qms-alloc-data
              mountPath: /qms/data/raft
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: qms-alloc-config
          configMap:
            name: qms-alloc-config
        - name: qms-alloc-data
          persistentVolumeClaim:
            claimName: qms-alloc-data
  volumeClaimTemplates:
    - metadata:
        name: qms-alloc-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi