apiVersion: v1
kind: ConfigMap
metadata:
  name: qms-config
data:
  config.yaml: |
    http_port: 6789
    otel_collector_target: grafana-agent-traces:4317
    allocation_quota_service:
      backend: local
      local:
        dir: /tmp/qms/data/alloc
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            capacity: 10

    rate_quota_service:
      backend: memory
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            algorithm: token-bucket
            unit: second
            requests_per_unit: 10
        - namespace: namespace2
          resource: resource2
          strategy:
            algorithm: token-bucket
            unit: second
            requests_per_unit: 10