apiVersion: v1
kind: ConfigMap
metadata:
  name: qms-config
data:
  config.yaml: |
    http_port: 6789

    allocation_quota_service:
      backend: memory
      quotas:
        - namespace: namespace1
          resource: resource2
          strategy:
            capacity: 10

    rate_quota_service:
      backend: memory
      quotas:
        - namespace: namespace1
          resource: resource1
          strategy:
            algorithm: token-bucket
            unit: second
            requests_per_unit: 10
        - namespace: namespace2
          resource: resource2
          strategy:
            algorithm: token-bucket
            unit: second
            requests_per_unit: 10