apiVersion: apps/v1
kind: Deployment
metadata:
  name: qms
  labels:
    app: qms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qms
  template:
    metadata:
      labels:
        app: qms
    spec:
      containers:
        - name: qms
          image: qms:latest
          ports:
            - name: http
              containerPort: 6789
          volumeMounts:
            - name: qms-config
              mountPath: /app/configs
      volumes:
        - name: qms-config
          configMap:
            name: qms-config