{
 "title": "QMS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "metrics_data_source", "query": "prometheus" },
   { "name": "logs_data_source", "query": "loki" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values({cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values({cluster=\"$cluster\", namespace=\"$namespace\"}, app)"
    }
   },
   {
    "name": "modules",
    "query": "label_values({cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\"}, name)"
   },
   {
    "name": "interval",
    "query": "1s,5s,15s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "quantile", "query": "0.50,0.95,0.99" },
   {
    "name": "level",
    "query": "debug,info,warn,error,panic,fatal"
   },
   { "name": "metric_prefix", "query": "default_qms" }
  ]
 },
 "panels": [
  { "title": "Resources $modules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$modules.*\"}[$__rate_interval]\n    )\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$modules.*\"}\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "General $modules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n    rate(${metric_prefix}_requests_total{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"}[$__rate_interval])\n)\nby (result, name, http_method, http_status_code, http_route)\n",
     "legendFormat": "{{result}} {{name}} {{http_method}}  {{http_status_code}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n    sum(\n        rate(${metric_prefix}_requests_total{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\", result=\"success\"}[$__rate_interval])\n    ) by (name, http_method, http_route)\n/\n    sum(\n        rate(${metric_prefix}_requests_total{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"}[$__rate_interval])\n    ) by (name, http_method, http_route)\n) \n",
     "legendFormat": "{{name}} {{http_method}}  {{http_status_code}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Latency (φ$quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    $quantile,\n        sum(\n            rate(\n                ${metric_prefix}_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"}[$__rate_interval]\n            )\n        ) by (le, name, http_method, http_route)\n)\n",
     "legendFormat": "{{name}} {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        ${metric_prefix}_request_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"}[$__rate_interval]\n    )\n) by (le, name, http_method, http_route)\n/\nsum(\n    rate(\n        ${metric_prefix}_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"}[$__rate_interval]\n    )\n) by (le, name, http_method, http_route)\n\n",
     "legendFormat": "{{name}} {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Logs $modules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$level Logs Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(count_over_time({cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"} | json | level=~\"$level\" [$__interval])) by (name, level)",
       "legendFormat": "{{name}} {{level}}"
      }
     ]
    },
    {
     "title": "$level Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"} | json | level=~\"$level\"",
       "resolution": 1
      }
     ]
    },
    {
     "title": "$modules Error Logs Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(count_over_time({cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"} | json | level=~\"error|panic|fatal\" [$__interval])) by (name, level)",
       "legendFormat": "{{name}} {{level}}"
      }
     ]
    },
    {
     "title": "Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"} | json | level=~\"error|panic|fatal\"",
       "resolution": 1
      }
     ]
    },
    {
     "title": "$modules Warn Logs Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(count_over_time({cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"} | json | level=~\"warn\" [$__interval])) by (name, level)",
       "legendFormat": "{{name}} {{level}}"
      }
     ]
    },
    {
     "title": "Warn Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"} | json | level=~\"warn\"",
       "resolution": 1
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime $modules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Heap Alloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    go_memstats_heap_alloc_bytes{cluster=\"$cluster\", namespace=\"$namespace\", app=\"$app\", name=~\"$modules\"}\n) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}